import os

from dotenv import load_dotenv

load_dotenv()

DEFAULT_PRINTER = os.getenv("DEFAULT_PRINTER", "mahingsa_printer")  
PRINTER_PORT1 = os.getenv("PRINTER_PORT1", DEFAULT_PRINTER)  
PRINTER_PORT2 = os.getenv("PRINTER_PORT2", DEFAULT_PRINTER)  
PRINTER_PORT3 = os.getenv("PRINTER_PORT3", DEFAULT_PRINTER)  
PRINTER_PORT4 = os.getenv("PRINTER_PORT4", DEFAULT_PRINTER)  
PRINTER_PORT5 = os.getenv("PRINTER_PORT5", DEFAULT_PRINTER)  
PRINTER_PORT6 = os.getenv("PRINTER_PORT6", DEFAULT_PRINTER)  
PRINTER_PORT7 = os.getenv("PRINTER_PORT7", DEFAULT_PRINTER)  
PRINTER_PORT8 = os.getenv("PRINTER_PORT8", DEFAULT_PRINTER)  
PRINTER_PORT9 = os.getenv("PRINTER_PORT9", DEFAULT_PRINTER)  
PRINTER_PORT10 = os.getenv("PRINTER_PORT10", DEFAULT_PRINTER)  

PRINTER_PORT_LIST = [DEFAULT_PRINTER, PRINTER_PORT1, PRINTER_PORT2, PRINTER_PORT3, PRINTER_PORT4, PRINTER_PORT5, PRINTER_PORT6, PRINTER_PORT7, PRINTER_PORT8, PRINTER_PORT9, PRINTER_PORT10]
